# Generated by Django 4.0.4 on 2022-04-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='working_mode',
            field=models.CharField(max_length=50, null=True, verbose_name='Режим работы'),
        ),
    ]
