# Generated by Django 4.0.4 on 2022-04-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_user_working_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+37533123456', max_length=50, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='working_mode',
            field=models.CharField(default='Понедельник - воскресенье 8:00 - 21:00', max_length=50, null=True, verbose_name='Режим работы'),
        ),
    ]
