# Generated by Django 4.0.4 on 2022-04-27 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Предложение')),
            ],
            options={
                'verbose_name': 'Предложение услуги',
                'verbose_name_plural': 'Предложения услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название услуги')),
                ('time', models.CharField(max_length=30, verbose_name='Время услуги')),
                ('price', models.CharField(max_length=30, verbose_name='Стоимость услуги за полный цикл')),
                ('warranty', models.CharField(max_length=50, verbose_name='Гарантия')),
                ('text', models.TextField(verbose_name='Информация об услуге')),
                ('type', models.CharField(choices=[('repair', 'Ремонт'), ('service', 'Услуги'), ('electric', 'Автоэлектрика')], max_length=60, verbose_name='Тип услуги')),
                ('contacts', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('suggestions', models.ManyToManyField(to='services.servicesuggestion', verbose_name='Предложения')),
            ],
            options={
                'verbose_name': 'Тип услуги',
                'verbose_name_plural': 'Типы услуг',
            },
        ),
    ]
