# Generated by Django 4.0.4 on 2022-04-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicegallery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='preview_text',
            field=models.TextField(null=True, verbose_name='Текст для превью'),
        ),
    ]
